apiVersion: v1
kind: Service
metadata:
  name: {{ include "appencorrect.fullname" . }}-service
  labels:
    {{- include "appencorrect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "appencorrect.selectorLabels" . | nindent 4 }}
